/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CourseCategory = IDL.Variant({
  'cds' : IDL.Null,
  'kvs' : IDL.Null,
  'nda' : IDL.Null,
  'nvs' : IDL.Null,
  'otherStatesPolice' : IDL.Null,
  'mppcs' : IDL.Null,
  'mptet' : IDL.Null,
  'tnpsc' : IDL.Null,
  'nabard' : IDL.Null,
  'tspsc' : IDL.Null,
  'otherStatesPCS' : IDL.Null,
  'afcat' : IDL.Null,
  'appsc' : IDL.Null,
  'agniveer' : IDL.Null,
  'rbiGradeB' : IDL.Null,
  'rpfConstable' : IDL.Null,
  'bpsc' : IDL.Null,
  'capf' : IDL.Null,
  'ctet' : IDL.Null,
  'biharPolice' : IDL.Null,
  'gpsc' : IDL.Null,
  'hpsc' : IDL.Null,
  'cgpsc' : IDL.Null,
  'htet' : IDL.Null,
  'jpsc' : IDL.Null,
  'kpsc' : IDL.Null,
  'mpsc' : IDL.Null,
  'navy' : IDL.Null,
  'reet' : IDL.Null,
  'rpsc' : IDL.Null,
  'upsc' : IDL.Null,
  'airforce' : IDL.Null,
  'rajasthanPolice' : IDL.Null,
  'stateTET' : IDL.Null,
  'ibpsClerk' : IDL.Null,
  'sscCGL' : IDL.Null,
  'sscCPO' : IDL.Null,
  'sscMTS' : IDL.Null,
  'sbiClerk' : IDL.Null,
  'university_geography' : IDL.Null,
  'sbiPO' : IDL.Null,
  'keralaPSC' : IDL.Null,
  'rrbALP' : IDL.Null,
  'upPolice' : IDL.Null,
  'sscGD' : IDL.Null,
  'sscJE' : IDL.Null,
  'rrbGroupD' : IDL.Null,
  'ukpsc' : IDL.Null,
  'uppcs' : IDL.Null,
  'uptet' : IDL.Null,
  'delhiPolice' : IDL.Null,
  'sscConstable' : IDL.Null,
  'rrbTechnician' : IDL.Null,
  'ibpsPO' : IDL.Null,
  'mpPolice' : IDL.Null,
  'rrbNTPC' : IDL.Null,
  'wbpsc' : IDL.Null,
  'punjabPSC' : IDL.Null,
  'sscStenographer' : IDL.Null,
  'sscCHSL' : IDL.Null,
  'dsssb' : IDL.Null,
  'licAAO' : IDL.Null,
  'rpfSI' : IDL.Null,
  'superTET' : IDL.Null,
  'rrbJE' : IDL.Null,
  'sscSelectionPost' : IDL.Null,
  'haryanaPolice' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CurrentAffairsType = IDL.Variant({
  'monthlyMagazine' : IDL.Null,
  'dailyUpdate' : IDL.Null,
  'weeklyPDF' : IDL.Null,
});
export const Subject = IDL.Variant({
  'economy' : IDL.Null,
  'history' : IDL.Null,
  'geography' : IDL.Null,
  'currentAffairs' : IDL.Null,
  'polity' : IDL.Null,
  'science' : IDL.Null,
});
export const AssessmentType = IDL.Variant({
  'dailyQuiz' : IDL.Null,
  'weeklyTest' : IDL.Null,
  'fullLengthTest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CurrentAffair = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'type' : CurrentAffairsType,
});
export const LeadershipImage = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'position' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'file' : ExternalBlob,
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'enrolledCourses' : IDL.Vec(IDL.Nat),
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'youtubeLink' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'pyq' : IDL.Vec(ExternalBlob),
  'testSeries' : IDL.Vec(IDL.Text),
  'notes' : IDL.Vec(ExternalBlob),
  'category' : CourseCategory,
  'videoLectures' : IDL.Vec(IDL.Text),
  'syllabus' : IDL.Vec(IDL.Text),
});
export const Logo = IDL.Vec(IDL.Nat8);
export const StaticContent = IDL.Record({
  'contactInfo' : IDL.Text,
  'aboutUs' : IDL.Text,
  'footerText' : IDL.Text,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'assessmentType' : AssessmentType,
  'questions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func(
      [
        CourseCategory,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Vec(ExternalBlob),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addCurrentAffair' : IDL.Func(
      [CurrentAffairsType, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addLeadershipImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addNote' : IDL.Func([Subject, ExternalBlob], [], []),
  'addTest' : IDL.Func([AssessmentType, IDL.Vec(IDL.Text)], [], []),
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteCurrentAffair' : IDL.Func([IDL.Nat], [], []),
  'deleteLeadershipImage' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'enrollCourse' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllCurrentAffairs' : IDL.Func([], [IDL.Vec(CurrentAffair)], ['query']),
  'getAllLeadershipImages' : IDL.Func(
      [],
      [IDL.Vec(LeadershipImage)],
      ['query'],
    ),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCoursesByCategory' : IDL.Func(
      [CourseCategory],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getCurrentAffairsByType' : IDL.Func(
      [CurrentAffairsType],
      [IDL.Vec(CurrentAffair)],
      ['query'],
    ),
  'getLeadershipImage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LeadershipImage)],
      ['query'],
    ),
  'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
  'getSortedCoursesByCategory' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getSortedCoursesByNumLectures' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getStaticContent' : IDL.Func([], [StaticContent], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [StudentProfile], ['query']),
  'getTestsByType' : IDL.Func([AssessmentType], [IDL.Vec(Test)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCourse' : IDL.Func(
      [
        IDL.Nat,
        CourseCategory,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Vec(ExternalBlob),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateCurrentAffair' : IDL.Func(
      [IDL.Nat, CurrentAffairsType, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateLeadershipImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLogo' : IDL.Func([Logo], [], []),
  'updateNote' : IDL.Func([IDL.Nat, Subject, ExternalBlob], [], []),
  'updateStaticContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTest' : IDL.Func([IDL.Nat, AssessmentType, IDL.Vec(IDL.Text)], [], []),
  'updateVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CourseCategory = IDL.Variant({
    'cds' : IDL.Null,
    'kvs' : IDL.Null,
    'nda' : IDL.Null,
    'nvs' : IDL.Null,
    'otherStatesPolice' : IDL.Null,
    'mppcs' : IDL.Null,
    'mptet' : IDL.Null,
    'tnpsc' : IDL.Null,
    'nabard' : IDL.Null,
    'tspsc' : IDL.Null,
    'otherStatesPCS' : IDL.Null,
    'afcat' : IDL.Null,
    'appsc' : IDL.Null,
    'agniveer' : IDL.Null,
    'rbiGradeB' : IDL.Null,
    'rpfConstable' : IDL.Null,
    'bpsc' : IDL.Null,
    'capf' : IDL.Null,
    'ctet' : IDL.Null,
    'biharPolice' : IDL.Null,
    'gpsc' : IDL.Null,
    'hpsc' : IDL.Null,
    'cgpsc' : IDL.Null,
    'htet' : IDL.Null,
    'jpsc' : IDL.Null,
    'kpsc' : IDL.Null,
    'mpsc' : IDL.Null,
    'navy' : IDL.Null,
    'reet' : IDL.Null,
    'rpsc' : IDL.Null,
    'upsc' : IDL.Null,
    'airforce' : IDL.Null,
    'rajasthanPolice' : IDL.Null,
    'stateTET' : IDL.Null,
    'ibpsClerk' : IDL.Null,
    'sscCGL' : IDL.Null,
    'sscCPO' : IDL.Null,
    'sscMTS' : IDL.Null,
    'sbiClerk' : IDL.Null,
    'university_geography' : IDL.Null,
    'sbiPO' : IDL.Null,
    'keralaPSC' : IDL.Null,
    'rrbALP' : IDL.Null,
    'upPolice' : IDL.Null,
    'sscGD' : IDL.Null,
    'sscJE' : IDL.Null,
    'rrbGroupD' : IDL.Null,
    'ukpsc' : IDL.Null,
    'uppcs' : IDL.Null,
    'uptet' : IDL.Null,
    'delhiPolice' : IDL.Null,
    'sscConstable' : IDL.Null,
    'rrbTechnician' : IDL.Null,
    'ibpsPO' : IDL.Null,
    'mpPolice' : IDL.Null,
    'rrbNTPC' : IDL.Null,
    'wbpsc' : IDL.Null,
    'punjabPSC' : IDL.Null,
    'sscStenographer' : IDL.Null,
    'sscCHSL' : IDL.Null,
    'dsssb' : IDL.Null,
    'licAAO' : IDL.Null,
    'rpfSI' : IDL.Null,
    'superTET' : IDL.Null,
    'rrbJE' : IDL.Null,
    'sscSelectionPost' : IDL.Null,
    'haryanaPolice' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CurrentAffairsType = IDL.Variant({
    'monthlyMagazine' : IDL.Null,
    'dailyUpdate' : IDL.Null,
    'weeklyPDF' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'economy' : IDL.Null,
    'history' : IDL.Null,
    'geography' : IDL.Null,
    'currentAffairs' : IDL.Null,
    'polity' : IDL.Null,
    'science' : IDL.Null,
  });
  const AssessmentType = IDL.Variant({
    'dailyQuiz' : IDL.Null,
    'weeklyTest' : IDL.Null,
    'fullLengthTest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CurrentAffair = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'type' : CurrentAffairsType,
  });
  const LeadershipImage = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'position' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'file' : ExternalBlob,
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'enrolledCourses' : IDL.Vec(IDL.Nat),
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'youtubeLink' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'pyq' : IDL.Vec(ExternalBlob),
    'testSeries' : IDL.Vec(IDL.Text),
    'notes' : IDL.Vec(ExternalBlob),
    'category' : CourseCategory,
    'videoLectures' : IDL.Vec(IDL.Text),
    'syllabus' : IDL.Vec(IDL.Text),
  });
  const Logo = IDL.Vec(IDL.Nat8);
  const StaticContent = IDL.Record({
    'contactInfo' : IDL.Text,
    'aboutUs' : IDL.Text,
    'footerText' : IDL.Text,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'assessmentType' : AssessmentType,
    'questions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func(
        [
          CourseCategory,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Vec(ExternalBlob),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addCurrentAffair' : IDL.Func(
        [CurrentAffairsType, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'addLeadershipImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addNote' : IDL.Func([Subject, ExternalBlob], [], []),
    'addTest' : IDL.Func([AssessmentType, IDL.Vec(IDL.Text)], [], []),
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteCurrentAffair' : IDL.Func([IDL.Nat], [], []),
    'deleteLeadershipImage' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'enrollCourse' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllCurrentAffairs' : IDL.Func([], [IDL.Vec(CurrentAffair)], ['query']),
    'getAllLeadershipImages' : IDL.Func(
        [],
        [IDL.Vec(LeadershipImage)],
        ['query'],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCoursesByCategory' : IDL.Func(
        [CourseCategory],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCurrentAffairsByType' : IDL.Func(
        [CurrentAffairsType],
        [IDL.Vec(CurrentAffair)],
        ['query'],
      ),
    'getLeadershipImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LeadershipImage)],
        ['query'],
      ),
    'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
    'getSortedCoursesByCategory' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getSortedCoursesByNumLectures' : IDL.Func(
        [],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getStaticContent' : IDL.Func([], [StaticContent], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [StudentProfile], ['query']),
    'getTestsByType' : IDL.Func([AssessmentType], [IDL.Vec(Test)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCourse' : IDL.Func(
        [
          IDL.Nat,
          CourseCategory,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Vec(ExternalBlob),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateCurrentAffair' : IDL.Func(
        [IDL.Nat, CurrentAffairsType, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateLeadershipImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLogo' : IDL.Func([Logo], [], []),
    'updateNote' : IDL.Func([IDL.Nat, Subject, ExternalBlob], [], []),
    'updateStaticContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTest' : IDL.Func(
        [IDL.Nat, AssessmentType, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };