/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssessmentType = { 'dailyQuiz' : null } |
  { 'weeklyTest' : null } |
  { 'fullLengthTest' : null };
export interface Course {
  'id' : bigint,
  'pyq' : Array<ExternalBlob>,
  'testSeries' : Array<string>,
  'notes' : Array<ExternalBlob>,
  'category' : CourseCategory,
  'videoLectures' : Array<string>,
  'syllabus' : Array<string>,
}
export type CourseCategory = { 'cds' : null } |
  { 'kvs' : null } |
  { 'nda' : null } |
  { 'nvs' : null } |
  { 'otherStatesPolice' : null } |
  { 'mppcs' : null } |
  { 'mptet' : null } |
  { 'tnpsc' : null } |
  { 'nabard' : null } |
  { 'tspsc' : null } |
  { 'otherStatesPCS' : null } |
  { 'afcat' : null } |
  { 'appsc' : null } |
  { 'agniveer' : null } |
  { 'rbiGradeB' : null } |
  { 'rpfConstable' : null } |
  { 'bpsc' : null } |
  { 'capf' : null } |
  { 'ctet' : null } |
  { 'biharPolice' : null } |
  { 'gpsc' : null } |
  { 'hpsc' : null } |
  { 'cgpsc' : null } |
  { 'htet' : null } |
  { 'jpsc' : null } |
  { 'kpsc' : null } |
  { 'mpsc' : null } |
  { 'navy' : null } |
  { 'reet' : null } |
  { 'rpsc' : null } |
  { 'upsc' : null } |
  { 'airforce' : null } |
  { 'rajasthanPolice' : null } |
  { 'stateTET' : null } |
  { 'ibpsClerk' : null } |
  { 'sscCGL' : null } |
  { 'sscCPO' : null } |
  { 'sscMTS' : null } |
  { 'sbiClerk' : null } |
  { 'university_geography' : null } |
  { 'sbiPO' : null } |
  { 'keralaPSC' : null } |
  { 'rrbALP' : null } |
  { 'upPolice' : null } |
  { 'sscGD' : null } |
  { 'sscJE' : null } |
  { 'rrbGroupD' : null } |
  { 'ukpsc' : null } |
  { 'uppcs' : null } |
  { 'uptet' : null } |
  { 'delhiPolice' : null } |
  { 'sscConstable' : null } |
  { 'rrbTechnician' : null } |
  { 'ibpsPO' : null } |
  { 'mpPolice' : null } |
  { 'rrbNTPC' : null } |
  { 'wbpsc' : null } |
  { 'punjabPSC' : null } |
  { 'sscStenographer' : null } |
  { 'sscCHSL' : null } |
  { 'dsssb' : null } |
  { 'licAAO' : null } |
  { 'rpfSI' : null } |
  { 'superTET' : null } |
  { 'rrbJE' : null } |
  { 'sscSelectionPost' : null } |
  { 'haryanaPolice' : null };
export interface CurrentAffair {
  'id' : bigint,
  'content' : string,
  'file' : [] | [ExternalBlob],
  'type' : CurrentAffairsType,
}
export type CurrentAffairsType = { 'monthlyMagazine' : null } |
  { 'dailyUpdate' : null } |
  { 'weeklyPDF' : null };
export type ExternalBlob = Uint8Array;
export interface LeadershipImage {
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'position' : string,
}
export type Logo = Uint8Array;
export interface Note {
  'id' : bigint,
  'subject' : Subject,
  'file' : ExternalBlob,
}
export interface StaticContent {
  'contactInfo' : string,
  'aboutUs' : string,
  'footerText' : string,
}
export interface StudentProfile {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'enrolledCourses' : Array<bigint>,
}
export type Subject = { 'economy' : null } |
  { 'history' : null } |
  { 'geography' : null } |
  { 'currentAffairs' : null } |
  { 'polity' : null } |
  { 'science' : null };
export interface Test {
  'id' : bigint,
  'assessmentType' : AssessmentType,
  'questions' : Array<string>,
}
export interface UserProfile {
  'studentId' : [] | [bigint],
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'youtubeLink' : string,
  'description' : string,
  'category' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<
    [
      CourseCategory,
      Array<string>,
      Array<string>,
      Array<ExternalBlob>,
      Array<ExternalBlob>,
      Array<string>,
    ],
    undefined
  >,
  'addCurrentAffair' : ActorMethod<
    [CurrentAffairsType, string, [] | [ExternalBlob]],
    undefined
  >,
  'addLeadershipImage' : ActorMethod<
    [string, ExternalBlob, string, string],
    undefined
  >,
  'addNote' : ActorMethod<[Subject, ExternalBlob], undefined>,
  'addTest' : ActorMethod<[AssessmentType, Array<string>], undefined>,
  'addVideo' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteCurrentAffair' : ActorMethod<[bigint], undefined>,
  'deleteLeadershipImage' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteTest' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'enrollCourse' : ActorMethod<[bigint, bigint], undefined>,
  'getAllCurrentAffairs' : ActorMethod<[], Array<CurrentAffair>>,
  'getAllLeadershipImages' : ActorMethod<[], Array<LeadershipImage>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCoursesByCategory' : ActorMethod<[CourseCategory], Array<Course>>,
  'getCurrentAffairsByType' : ActorMethod<
    [CurrentAffairsType],
    Array<CurrentAffair>
  >,
  'getLeadershipImage' : ActorMethod<[string], [] | [LeadershipImage]>,
  'getLogo' : ActorMethod<[], [] | [Logo]>,
  'getNotesBySubject' : ActorMethod<[Subject], Array<Note>>,
  'getSortedCoursesByCategory' : ActorMethod<[], Array<Course>>,
  'getSortedCoursesByNumLectures' : ActorMethod<[], Array<Course>>,
  'getStaticContent' : ActorMethod<[], StaticContent>,
  'getStudent' : ActorMethod<[bigint], StudentProfile>,
  'getTestsByType' : ActorMethod<[AssessmentType], Array<Test>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<[string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCourse' : ActorMethod<
    [
      bigint,
      CourseCategory,
      Array<string>,
      Array<string>,
      Array<ExternalBlob>,
      Array<ExternalBlob>,
      Array<string>,
    ],
    undefined
  >,
  'updateCurrentAffair' : ActorMethod<
    [bigint, CurrentAffairsType, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateLeadershipImage' : ActorMethod<
    [string, ExternalBlob, string, string],
    undefined
  >,
  'updateLogo' : ActorMethod<[Logo], undefined>,
  'updateNote' : ActorMethod<[bigint, Subject, ExternalBlob], undefined>,
  'updateStaticContent' : ActorMethod<[string, string, string], undefined>,
  'updateTest' : ActorMethod<
    [bigint, AssessmentType, Array<string>],
    undefined
  >,
  'updateVideo' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];