/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: bigint;
    title: string;
    youtubeLink: string;
    description: string;
    category: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Test {
    id: bigint;
    assessmentType: AssessmentType;
    questions: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Course {
    id: bigint;
    pyq: Array<ExternalBlob>;
    testSeries: Array<string>;
    notes: Array<ExternalBlob>;
    category: CourseCategory;
    videoLectures: Array<string>;
    syllabus: Array<string>;
}
export interface StudentProfile {
    id: bigint;
    name: string;
    email: string;
    enrolledCourses: Array<bigint>;
}
export type Logo = Uint8Array;
export interface CurrentAffair {
    id: bigint;
    content: string;
    file?: ExternalBlob;
    type: CurrentAffairsType;
}
export interface UserProfile {
    studentId?: bigint;
    name: string;
    email: string;
}
export interface Note {
    id: bigint;
    subject: Subject;
    file: ExternalBlob;
}
export enum AssessmentType {
    dailyQuiz = "dailyQuiz",
    weeklyTest = "weeklyTest",
    fullLengthTest = "fullLengthTest"
}
export enum CourseCategory {
    ssc = "ssc",
    railway = "railway",
    upsc = "upsc",
    banking = "banking",
    university_geography = "university_geography",
    uppcs = "uppcs",
    tet_ctet = "tet_ctet",
    nda_cds = "nda_cds",
    police = "police"
}
export enum CurrentAffairsType {
    monthlyMagazine = "monthlyMagazine",
    dailyUpdate = "dailyUpdate",
    weeklyPDF = "weeklyPDF"
}
export enum Subject {
    economy = "economy",
    history = "history",
    geography = "geography",
    currentAffairs = "currentAffairs",
    polity = "polity",
    science = "science"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCourse(category: CourseCategory, syllabus: Array<string>, videoLectures: Array<string>, notesFiles: Array<ExternalBlob>, pyqFiles: Array<ExternalBlob>, testSeries: Array<string>): Promise<void>;
    addCurrentAffair(type: CurrentAffairsType, content: string, file: ExternalBlob | null): Promise<void>;
    addNote(subject: Subject, file: ExternalBlob): Promise<void>;
    addTest(assessmentType: AssessmentType, questions: Array<string>): Promise<void>;
    addVideo(title: string, category: string, description: string, youtubeLink: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCourse(id: bigint): Promise<void>;
    deleteCurrentAffair(id: bigint): Promise<void>;
    deleteNote(id: bigint): Promise<void>;
    deleteTest(id: bigint): Promise<void>;
    deleteVideo(id: bigint): Promise<void>;
    enrollCourse(studentId: bigint, courseId: bigint): Promise<void>;
    getAllCurrentAffairs(): Promise<Array<CurrentAffair>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllStudents(): Promise<Array<StudentProfile>>;
    getAllVideos(): Promise<Array<Video>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoursesByCategory(category: CourseCategory): Promise<Array<Course>>;
    getCurrentAffairsByType(type: CurrentAffairsType): Promise<Array<CurrentAffair>>;
    getLogo(): Promise<Logo | null>;
    getNotesBySubject(subject: Subject): Promise<Array<Note>>;
    getSortedCoursesByCategory(): Promise<Array<Course>>;
    getSortedCoursesByNumLectures(): Promise<Array<Course>>;
    getStudent(id: bigint): Promise<StudentProfile>;
    getTestsByType(assessmentType: AssessmentType): Promise<Array<Test>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerStudent(name: string, email: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCourse(id: bigint, category: CourseCategory, syllabus: Array<string>, videoLectures: Array<string>, notesFiles: Array<ExternalBlob>, pyqFiles: Array<ExternalBlob>, testSeries: Array<string>): Promise<void>;
    updateCurrentAffair(id: bigint, type: CurrentAffairsType, content: string, file: ExternalBlob | null): Promise<void>;
    updateLogo(newLogo: Logo): Promise<void>;
    updateNote(id: bigint, subject: Subject, file: ExternalBlob): Promise<void>;
    updateTest(id: bigint, assessmentType: AssessmentType, questions: Array<string>): Promise<void>;
    updateVideo(id: bigint, title: string, category: string, description: string, youtubeLink: string): Promise<void>;
}
import type { AssessmentType as _AssessmentType, Course as _Course, CourseCategory as _CourseCategory, CurrentAffair as _CurrentAffair, CurrentAffairsType as _CurrentAffairsType, ExternalBlob as _ExternalBlob, Logo as _Logo, Note as _Note, Subject as _Subject, Test as _Test, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCourse(arg0: CourseCategory, arg1: Array<string>, arg2: Array<string>, arg3: Array<ExternalBlob>, arg4: Array<ExternalBlob>, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addCurrentAffair(arg0: CurrentAffairsType, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCurrentAffair(to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCurrentAffair(to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addNote(arg0: Subject, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addTest(arg0: AssessmentType, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTest(to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTest(to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addVideo(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCourse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteCurrentAffair(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCurrentAffair(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCurrentAffair(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteTest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async enrollCourse(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollCourse(arg0, arg1);
            return result;
        }
    }
    async getAllCurrentAffairs(): Promise<Array<CurrentAffair>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCurrentAffairs();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCurrentAffairs();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByCategory(arg0: CourseCategory): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByCategory(to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByCategory(to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentAffairsByType(arg0: CurrentAffairsType): Promise<Array<CurrentAffair>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentAffairsByType(to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentAffairsByType(to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogo(): Promise<Logo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogo();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogo();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesBySubject(arg0: Subject): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesBySubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesBySubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedCoursesByCategory(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedCoursesByCategory();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedCoursesByCategory();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedCoursesByNumLectures(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedCoursesByNumLectures();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedCoursesByNumLectures();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: bigint): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return result;
        }
    }
    async getTestsByType(arg0: AssessmentType): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestsByType(to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestsByType(to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCourse(arg0: bigint, arg1: CourseCategory, arg2: Array<string>, arg3: Array<string>, arg4: Array<ExternalBlob>, arg5: Array<ExternalBlob>, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, to_candid_CourseCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateCurrentAffair(arg0: bigint, arg1: CurrentAffairsType, arg2: string, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrentAffair(arg0, to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrentAffair(arg0, to_candid_CurrentAffairsType_n12(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateLogo(arg0: Logo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogo(arg0);
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: Subject, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTest(arg0: bigint, arg1: AssessmentType, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, to_candid_AssessmentType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateVideo(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AssessmentType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentType): AssessmentType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_CourseCategory_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseCategory): CourseCategory {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Course_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Promise<Course> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_CurrentAffair_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentAffair): Promise<CurrentAffair> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CurrentAffairsType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentAffairsType): CurrentAffairsType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Note_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Promise<Note> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Test_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Test): Test {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Logo]): Logo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    file: [] | [_ExternalBlob];
    type: _CurrentAffairsType;
}): Promise<{
    id: bigint;
    content: string;
    file?: ExternalBlob;
    type: CurrentAffairsType;
}> {
    return {
        id: value.id,
        content: value.content,
        file: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.file)),
        type: from_candid_CurrentAffairsType_n26(_uploadFile, _downloadFile, value.type)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: _Subject;
    file: _ExternalBlob;
}): Promise<{
    id: bigint;
    subject: Subject;
    file: ExternalBlob;
}> {
    return {
        id: value.id,
        subject: from_candid_Subject_n31(_uploadFile, _downloadFile, value.subject),
        file: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.file)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: [] | [bigint];
    name: string;
    email: string;
}): {
    studentId?: bigint;
    name: string;
    email: string;
} {
    return {
        studentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.studentId)),
        name: value.name,
        email: value.email
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pyq: Array<_ExternalBlob>;
    testSeries: Array<string>;
    notes: Array<_ExternalBlob>;
    category: _CourseCategory;
    videoLectures: Array<string>;
    syllabus: Array<string>;
}): Promise<{
    id: bigint;
    pyq: Array<ExternalBlob>;
    testSeries: Array<string>;
    notes: Array<ExternalBlob>;
    category: CourseCategory;
    videoLectures: Array<string>;
    syllabus: Array<string>;
}> {
    return {
        id: value.id,
        pyq: await from_candid_vec_n41(_uploadFile, _downloadFile, value.pyq),
        testSeries: value.testSeries,
        notes: await from_candid_vec_n41(_uploadFile, _downloadFile, value.notes),
        category: from_candid_CourseCategory_n42(_uploadFile, _downloadFile, value.category),
        videoLectures: value.videoLectures,
        syllabus: value.syllabus
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assessmentType: _AssessmentType;
    questions: Array<string>;
}): {
    id: bigint;
    assessmentType: AssessmentType;
    questions: Array<string>;
} {
    return {
        id: value.id,
        assessmentType: from_candid_AssessmentType_n48(_uploadFile, _downloadFile, value.assessmentType),
        questions: value.questions
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthlyMagazine: null;
} | {
    dailyUpdate: null;
} | {
    weeklyPDF: null;
}): CurrentAffairsType {
    return "monthlyMagazine" in value ? CurrentAffairsType.monthlyMagazine : "dailyUpdate" in value ? CurrentAffairsType.dailyUpdate : "weeklyPDF" in value ? CurrentAffairsType.weeklyPDF : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    economy: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    currentAffairs: null;
} | {
    polity: null;
} | {
    science: null;
}): Subject {
    return "economy" in value ? Subject.economy : "history" in value ? Subject.history : "geography" in value ? Subject.geography : "currentAffairs" in value ? Subject.currentAffairs : "polity" in value ? Subject.polity : "science" in value ? Subject.science : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ssc: null;
} | {
    railway: null;
} | {
    upsc: null;
} | {
    banking: null;
} | {
    university_geography: null;
} | {
    uppcs: null;
} | {
    tet_ctet: null;
} | {
    nda_cds: null;
} | {
    police: null;
}): CourseCategory {
    return "ssc" in value ? CourseCategory.ssc : "railway" in value ? CourseCategory.railway : "upsc" in value ? CourseCategory.upsc : "banking" in value ? CourseCategory.banking : "university_geography" in value ? CourseCategory.university_geography : "uppcs" in value ? CourseCategory.uppcs : "tet_ctet" in value ? CourseCategory.tet_ctet : "nda_cds" in value ? CourseCategory.nda_cds : "police" in value ? CourseCategory.police : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyQuiz: null;
} | {
    weeklyTest: null;
} | {
    fullLengthTest: null;
}): AssessmentType {
    return "dailyQuiz" in value ? AssessmentType.dailyQuiz : "weeklyTest" in value ? AssessmentType.weeklyTest : "fullLengthTest" in value ? AssessmentType.fullLengthTest : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CurrentAffair>): Promise<Array<CurrentAffair>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CurrentAffair_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Promise<Array<Note>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Note_n29(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Promise<Array<Course>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Course_n39(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Test>): Array<Test> {
    return value.map((x)=>from_candid_Test_n46(_uploadFile, _downloadFile, x));
}
function to_candid_AssessmentType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentType): _AssessmentType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_CourseCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseCategory): _CourseCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CurrentAffairsType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrentAffairsType): _CurrentAffairsType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Subject_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: bigint;
    name: string;
    email: string;
}): {
    studentId: [] | [bigint];
    name: string;
    email: string;
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        name: value.name,
        email: value.email
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrentAffairsType): {
    monthlyMagazine: null;
} | {
    dailyUpdate: null;
} | {
    weeklyPDF: null;
} {
    return value == CurrentAffairsType.monthlyMagazine ? {
        monthlyMagazine: null
    } : value == CurrentAffairsType.dailyUpdate ? {
        dailyUpdate: null
    } : value == CurrentAffairsType.weeklyPDF ? {
        weeklyPDF: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    economy: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    currentAffairs: null;
} | {
    polity: null;
} | {
    science: null;
} {
    return value == Subject.economy ? {
        economy: null
    } : value == Subject.history ? {
        history: null
    } : value == Subject.geography ? {
        geography: null
    } : value == Subject.currentAffairs ? {
        currentAffairs: null
    } : value == Subject.polity ? {
        polity: null
    } : value == Subject.science ? {
        science: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentType): {
    dailyQuiz: null;
} | {
    weeklyTest: null;
} | {
    fullLengthTest: null;
} {
    return value == AssessmentType.dailyQuiz ? {
        dailyQuiz: null
    } : value == AssessmentType.weeklyTest ? {
        weeklyTest: null
    } : value == AssessmentType.fullLengthTest ? {
        fullLengthTest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseCategory): {
    ssc: null;
} | {
    railway: null;
} | {
    upsc: null;
} | {
    banking: null;
} | {
    university_geography: null;
} | {
    uppcs: null;
} | {
    tet_ctet: null;
} | {
    nda_cds: null;
} | {
    police: null;
} {
    return value == CourseCategory.ssc ? {
        ssc: null
    } : value == CourseCategory.railway ? {
        railway: null
    } : value == CourseCategory.upsc ? {
        upsc: null
    } : value == CourseCategory.banking ? {
        banking: null
    } : value == CourseCategory.university_geography ? {
        university_geography: null
    } : value == CourseCategory.uppcs ? {
        uppcs: null
    } : value == CourseCategory.tet_ctet ? {
        tet_ctet: null
    } : value == CourseCategory.nda_cds ? {
        nda_cds: null
    } : value == CourseCategory.police ? {
        police: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
